### ISSUE TITLE
Feature request: possibility to make incremental measurements

### ISSUE THREAD

**Issue by mariush444** [BasicAirData/Clinometer#18]
It will be good to have possibility to set "zero reference" at any position of the phone.
It means that:
1.  phone is at position A
2. user clicks "0 button/icon" and any value at this position is 0,
3. then measurement is started referring to this 0 position.

**Comment by GrazianoCapelli** [comment]
@mariush444: As you see, this application is at an early stage of development; it currently implements some basic functionalities (measurement, locking, camera overlay, and a full matrix calibration routine); additional features will be implemented on the next releases, and feature requests are very welcome.

The incremental misurement is a feature that is often present in other clinometers, and it seems a great idea to implement.
The "0" button could be added to the upper toolbar, to allow the users to set/reset the relative zero to be used for the relative measurements.

**Comment by GrazianoCapelli** [comment]
We implemented the incremental measurement for vertical use (in camera and grid mode), where the feature is more often used. The horizontal part can also be implemented in a future release.

I suggest to keep open the issue to collect feedback about the solution for vertical use, but also ideas, mock-ups, and comments about the horizontal part that might be implemented,

**Comment by GrazianoCapelli** [comment]
I implemented also the horizontal incremental angle, by putting it in place of the absolute one (like for vertical angles).
The absolute horizontal angle has a range of 0 - 180 degrees (always positive), the incremental angle will have a sign (+ or -) depending on the difference between current and pinned.

![photo_2022-03-02_21-59-10](https://user-images.githubusercontent.com/6907566/156448882-fd575927-e42d-42d1-b177-d2d10627f32c.jpg)

I hope that it will be understandable by the users.

**Comment by GrazianoCapelli** [comment]
The new feature has been included into the update v1.2.0.

**Comment by mariush444** [comment]
Thank you.
