### ISSUE TITLE
Measure Incline "Keep screen vertical..."

### ISSUE THREAD

**Issue by Scot1967** [BasicAirData/Clinometer#28]
Hello,

Thanks enjoying the app so far.  Why, when using the camera and measuring an angel to a distant point on a hill, do I see a message, "Keep the screen vertical and tilt the device"?  Also the negative 669% value (roll axis?) on the screen is confusing in this mode.

Samsung A14. Android ver 14.

![image](https://github.com/BasicAirData/Clinometer/assets/170291687/ff4134a6-4c50-4fdc-91bf-1b2e6d495025)

**Comment by GrazianoCapelli** [comment]
Hi,
The user's feedback are a fundamental base to develop a good open source application.
Thus, first of all, thanks for your time.

We thought to use the camera only to measure tilts, like the following images:

![tilt_screen](https://github.com/BasicAirData/Clinometer/assets/6907566/163040fe-81a1-41de-8b68-4cfc94fafa64)

The left measurement is made in the right way (with the screen kept in vertical), but the right image shows a wrong way to make the same measurement (the screen is inclined, and the resulting number is not correct). We thought to add the tooltip to inform the user that it is making a measurement in a not proper way.

But the use you pointed out is correct and perfectly legal, but we didn't thought this kind of use.
I think that we best way might be to remove the tooltip, or not?

**Comment by Scot1967** [comment]
I see what the mesage means now.  Thank you.  If you think this use would be popular, then maybe this could be made a selectable option in the app settings.  In this way the other measurements that seem odd in this mode could be altered or suppressed.

Thanks!
